# Generated by Django 5.2.5 on 2025-09-20 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="currency",
            field=models.CharField(default="KES", max_length=3),
        ),
        migrations.AlterField(
            model_name="payment",
            name="failure_reason",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="payment",
            name="paystack_access_code",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="payment",
            name="paystack_reference",
            field=models.CharField(blank=True, default="", max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="payment",
            name="paystack_transaction_id",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
