# Generated by Django 5.2.5 on 2025-09-20 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "payments",
            "0002_alter_payment_currency_alter_payment_failure_reason_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="failure_reason",
            field=models.TextField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name="payment",
            name="paystack_reference",
            field=models.CharField(
                blank=True, default=None, max_length=100, unique=True
            ),
        ),
    ]
