# Generated by Django 5.2.5 on 2025-09-20 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0003_alter_payment_failure_reason_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="failure_reason",
            field=models.TextField(blank=True, default=""),
        ),
    ]
