# Generated by Django 5.2.5 on 2025-08-15 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_order_delivered_at_order_shipped_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="shipping_method",
            field=models.CharField(
                choices=[
                    ("standard", "Standard Shipping"),
                    ("express", "Express Shipping"),
                ],
                default="standard",
                max_length=20,
            ),
        ),
    ]
