# Generated by Django 5.2.5 on 2025-09-20 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_order_shipping_method"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="notes",
            field=models.TextField(blank=True, default=""),
        ),
    ]
