name: Sokoni CI/CD Pipeline
run-name: ${{ github.actor }} is deploying Sokoni on Branch ${{ github.ref }} 🚀
on:
    push:
        branches: [ main, staging, development ]

jobs:
  test:
    name: Run Django Tests
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."
      - run: echo "🐧 This job is now running on a ${{ runner.os }} server hosted by GitHub!"
      - name: Check out repository code
        uses: actions/checkout@v5
      - run: echo "💡 The ${{ github.repository }} repository has been cloned to the runner."

      - name: Setup Python Environment
        uses: actions/setup-python@v4
        with:
            python-version: 3.12

      - name: Cache Python Deps
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Python Deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Tests
        env:
          DATABASE_URL: ${{ secrets.TEST_DB_URL }}
        run: |
          python manage.py test

  build:
    permissions:
      id-token: write
      contents: read

    name: Build and Push Docker Image
    needs: test
    runs-on: ubuntu-latest
    outputs:
      image_uri: ${{ steps.set-image.outputs.image_uri }}
      environment: ${{ steps.set-env.outputs.environment }}
      tf_workspace: ${{ steps.set-env.outputs.tf_workspace }}
      config_directory: ${{ steps.set-env.outputs.config_directory }}

    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Set Environment Vars
        id: set-env
        run: |
          if [[ "${{ github.ref_name }}" == "main" ]]; then
            echo "environment=production" >> $GITHUB_OUTPUT
            echo "tf_workspace=sokoni-production" >> $GITHUB_OUTPUT
            echo "config_directory=./.github/infra/prod" >> $GITHUB_OUTPUT
          elif [[ "${{ github.ref_name }}" == "staging" ]]; then
            echo "environment=staging" >> $GITHUB_OUTPUT
            echo "tf_workspace=sokoni-staging" >> $GITHUB_OUTPUT
            echo "config_directory=./.github/infra/staging" >> $GITHUB_OUTPUT
          else
            echo "environment=development" >> $GITHUB_OUTPUT
            echo "tf_workspace=sokoni-staging" >> $GITHUB_OUTPUT
            echo "config_directory=./.github/infra/staging" >> $GITHUB_OUTPUT
          fi

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ECR_ROLE_ARN }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Image
        run: |
          docker build -t ${{ steps.login-ecr.outputs.registry }}/${{ vars.DOCKERHUB_USERNAME }}/${{ vars.DOCKER_IMAGE_NAME }}:${{ github.ref_name }}-${{ github.sha }} -t ${{ steps.login-ecr.outputs.registry }}/${{ vars.DOCKERHUB_USERNAME }}/${{ vars.DOCKER_IMAGE_NAME }}:${{ github.ref_name }}-latest .

      - name: Run Trivy Vulnerability Scan - Unknown, Low, and Medium Severity
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: '${{ steps.login-ecr.outputs.registry }}/${{ vars.DOCKERHUB_USERNAME }}/${{ vars.DOCKER_IMAGE_NAME }}:${{ github.ref_name }}-${{ github.sha }}'
          exit-code: 0
          severity: 'UNKNOWN,LOW,MEDIUM'

      - name: Run Trivy Vulnerability Scan - High and Critical Severity
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: '${{ steps.login-ecr.outputs.registry }}/${{ vars.DOCKERHUB_USERNAME }}/${{ vars.DOCKER_IMAGE_NAME }}:${{ github.ref_name }}-${{ github.sha }}'
          format: 'github'
          exit-code: 1
          severity: 'CRITICAL,HIGH'

      - name: Run Django Check
        run: |
          docker run \
          -e DATABASE_URL=${{ secrets.TEST_DB_URL }} \
          --rm ${{ steps.login-ecr.outputs.registry }}/${{ vars.DOCKERHUB_USERNAME }}/${{ vars.DOCKER_IMAGE_NAME }}:${{ github.ref_name }}-${{ github.sha }} \
          python manage.py check

      - name: Push Image to AWS_ECR
        env:
          AWS_ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        run: |
          docker push --all-tags $AWS_ECR_REGISTRY/${{ vars.DOCKERHUB_USERNAME }}/${{ vars.DOCKER_IMAGE_NAME }}

      - name: Set container_image variable in Terraform Cloud
        env:
          TF_CLOUD_ORGANIZATION: victorgpt0
          TF_WORKSPACE: ${{ steps.set-env.outputs.tf_workspace }}
          TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
          IMAGE_URI: ${{ steps.login-ecr.outputs.registry }}/${{ vars.DOCKERHUB_USERNAME }}/${{ vars.DOCKER_IMAGE_NAME }}:${{ github.ref_name }}-${{ github.sha }}
          TF_IMAGE_VAR_ID: ${{ github.ref_name == 'main' && secrets.TF_MAIN_IMAGE_VAR_ID || secrets.TF_STAGING_IMAGE_VAR_ID }}
          TF_WORKSPACE_ID: ${{ github.ref_name == 'main' && secrets.TF_MAIN_WORKSPACE_ID || secrets.TF_STAGING_WORKSPACE_ID }}
        run: |
          curl \
          --header "Authorization: Bearer $TF_API_TOKEN" \
          --header "Content-Type: application/vnd.api+json" \
          --request PATCH \
          --data @- \
          https://app.terraform.io/api/v2/workspaces/$TF_WORKSPACE_ID/vars/$TF_IMAGE_VAR_ID <<EOF
          {
            "data": {
              "id":"$TF_IMAGE_VAR_ID",
              "attributes": {
                "key":"container_image",
                "value":"$IMAGE_URI",
                "description":"container image URI for the ECS service",
                "category":"terraform",
                "hcl": false,
                "sensitive": false
              },
              "type":"vars"
            }
          }
          EOF


  plan-deploy:

    name: Terraform Plan
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read
    env:
      TF_CLOUD_ORGANIZATION: victorgpt0
      TF_WORKSPACE: ${{ needs.build.outputs.tf_workspace }}
      TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
      CONFIG_DIRECTORY: ${{ needs.build.outputs.config_directory }}

    steps:

      - name: Checkout
        uses: actions/checkout@v5

      - name: Upload Configuration to Terraform Cloud
        uses: hashicorp/tfc-workflows-github/actions/upload-configuration@v1.0.0
        id: plan-upload
        with:
          workspace: ${{ env.TF_WORKSPACE }}
          directory: ${{ env.CONFIG_DIRECTORY }}
          speculative: true

      - name: Create Plan Run
        uses: hashicorp/tfc-workflows-github/actions/create-run@v1.0.0
        id: plan-run
        with:
          workspace: ${{ env.TF_WORKSPACE }}
          configuration_version: ${{ steps.plan-upload.outputs.configuration_version_id }}
          plan_only: true

      - name: Get Plan Output
        uses: hashicorp/tfc-workflows-github/actions/plan-output@v1.0.0
        with:
          plan: ${{ fromJSON(steps.plan-run.outputs.payload).data.relationships.plan.data.id }}

  deploy:
    name: Terraform Apply
    runs-on: ubuntu-latest
    needs: plan-deploy
    permissions:
      id-token: write
      contents: read
    env:
      TF_CLOUD_ORGANIZATION: victorgpt0
      TF_WORKSPACE: ${{ needs.build.outputs.tf_workspace }}
      TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
      CONFIG_DIRECTORY: ${{ needs.build.outputs.config_directory }}

    steps:

      - name: Checkout
        uses: actions/checkout@v5

      - name: Upload Configuration
        uses: hashicorp/tfc-workflows-github/actions/upload-configuration@v1.0.0
        id: apply-upload
        with:
          workspace: ${{ env.TF_WORKSPACE }}
          directory: ${{ env.CONFIG_DIRECTORY }}

      - name: Create Apply Run
        uses: hashicorp/tfc-workflows-github/actions/create-run@v1.0.0
        id: apply-run
        with:
          workspace: ${{ env.TF_WORKSPACE }}
          configuration_version: ${{ steps.apply-upload.outputs.configuration_version_id }}

      - name: Apply
        uses: hashicorp/tfc-workflows-github/actions/apply-run@v1.0.0
        if: fromJSON(steps.apply-run.outputs.payload).data.attributes.actions.IsConfirmable
        id: apply
        with:
          run: ${{ steps.apply-run.outputs.run_id }}
          comment: "Apply Run from GitHub Actions CI ${{ github.sha }}"
