name: SAST Scan
run-name: Static App Security Testing on Sokoni 🧿
on:
  push:
    branches: [ main, staging, development ]
  pull_request:
    types: [opened, synchronize, reopened]
  schedule: 
    - cron: '0 0 * * 0'

jobs:
  codeql:
    name: CodeQL Analysis
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
      contents: read
    
    strategy:
      fail-fast: false
      matrix:
        language: [python]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Init CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: ${{ matrix.language }}
      
      - name: Build Pip Deps
        run: |
          pip install -r requirements.txt
      
      - name: Perform Analysis
        uses: github/codeql-action/analyze@v3
        with:
          upload: false
          
      - name: Show SARIF results
        run: cat ./results/*.sarif



  sonarqube:
    name: SonarQube
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}