name: Trivy Docker Image Scan
run-name: Trivy is scanning Sokoni Docker Image 🐋

on: 
    push:
        branches: [ main, staging, development ]
    schedule:
        - cron: $cron-weekly

permissions:
    security-events: write
    actions: read
    contents: read

jobs:
    trivy-scan:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v5

            - name: Setup Docker Buildx
              uses: docker/setup-buildx-action@v3
      
            - name: Build Docker Image
              run: |
                docker build -t ${{ vars.DOCKERHUB_USERNAME }}/${{ vars.DOCKER_IMAGE_NAME }}:${{ github.ref_name }}-${{ github.sha }} .

            - name: Run Trivy Vulnerability Scanner
              uses: aquasecurity/trivy-action@0.28.0
              with:
                image-ref: '${{ vars.DOCKERHUB_USERNAME }}/${{ vars.DOCKER_IMAGE_NAME }}:${{ github.ref_name }}-${{ github.sha }}'
                format: 'template'
                template: '@/contrib/sarif.tp1'
                output: 'trivy-results.sarif'
                severity: 'CRITICAL,HIGH'
            
            - name: Upload Results to GitHub Security
              uses: github/codeql-action/upload-sarif@v3
              with: 
                sarif_file: 'trivy-results.sarif'

