# Generated by Django 5.2.5 on 2025-08-18 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "products",
            "0003_remove_product_products_product_stock_quantity_non_negative_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="products",
                to="auth.user",
            ),
        ),
    ]
